### ISSUE TITLE
Dimension mismatch error in bertU

### ISSUE THREAD

**Issue by samyakag** [Muennighoff/vilio#8]
While running UNITER with bert, I am encountering this dimension error. I am not sure but it seems to me that it is happening because the input is not getting truncated in the entryU.py file like it is getting in entry files of other models.

Traceback (most recent call last):
  File "hm.py", line 392, in <module>
    main()
  File "hm.py", line 359, in main
    hm.train(hm.train_tuple, hm.valid_tuple)
  File "hm.py", line 186, in train
    logit = self.model(sent, (feats, boxes))
  File "/home/samyakxd/miniconda3/envs/vilio_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch/samyakxd/vilio/entryU.py", line 200, in forward
    seq_out, pooled_output = self.model(input_ids.cuda(), None, img_feats.cuda(), img_pos_feats.cuda(), attn_masks.cuda(), gather_index=gather_index.cuda())
  File "/home/samyakxd/miniconda3/envs/vilio_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch/samyakxd/vilio/src/vilio/modeling_bertU.py", line 416, in forward
    gather_index, txt_type_ids, img_type_ids)
  File "/scratch/samyakxd/vilio/src/vilio/modeling_bertU.py", line 360, in _compute_img_txt_embeddings
    input_ids, position_ids, txt_type_ids)
  File "/scratch/samyakxd/vilio/src/vilio/modeling_bertU.py", line 330, in _compute_txt_embeddings
    output = self.embeddings(input_ids, position_ids, txt_type_ids)
  File "/home/samyakxd/miniconda3/envs/vilio_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch/samyakxd/vilio/src/vilio/modeling_bertU.py", line 257, in forward
    embeddings = inputs_embeds + position_embeddings + token_type_embeddings
RuntimeError: The size of tensor a (557) must match the size of tensor b (512) at non-singleton dimension 1

**Comment by Muennighoff** [comment]
It seems like you are right indeed - Does it work correctly for other examples?
If yes, you may need to truncate all your texts to 512 tokens (either by adding it in the code or doing it ahead of time)~

**Comment by samyakag** [comment]
Yes it does. I did truncate the input and it seems to be working now.
